### ISSUE TITLE
NHI button no longer works (server down/dead?)

### ISSUE THREAD

**Issue by Huite** [Deltares/imod-qgis#55]
Clicking the NHI button results in the following stacktrace:

```python
Traceback (most recent call last):
  File "C:\Users/bootsma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\imodqgis\imod_plugin.py", line 106, in nhi_data_dialog
    dialog = ImodNhiDataDialog(self.iface)
  File "C:\Users/bootsma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\imodqgis\nhi_data\nhi_data_dialog.py", line 84, in __init__
    self.load_services()
  File "C:\Users/bootsma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\imodqgis\nhi_data\nhi_data_dialog.py", line 148, in load_services
    fetch_metadata()
  File "C:\Users/bootsma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\imodqgis\nhi_data\provider_metadata.py", line 119, in fetch_metadata
    metadata.extend(functions[service](url, version))
  File "C:\Users/bootsma/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\imodqgis\nhi_data\provider_metadata.py", line 32, in wcs_metadata
    root = ElementTree.XML(response)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\xml\etree\ElementTree.py", line 1347, in XML
    parser.feed(text)
xml.etree.ElementTree.ParseError: mismatched tag: line 44, column 4
```

It seems reasonable to assume the that NHI data portal is down.

**Comment by Huite** [comment]
Current providers:

```python
PROVIDERS = [
    ("https://data.nhi.nu/geoserver/ows", "wcs", "2.0.1"),
    ("https://data.nhi.nu/geoserver/ows", "wfs", "2.0.0"),
    ("https://data.nhi.nu/geoserver/ows", "wms", "1.3.0"),
    ("https://modeldata-nhi-data.deltares.nl/geoserver/ows", "wcs", "2.0.1"),
    ("https://modeldata-nhi-data.deltares.nl/geoserver/ows", "wms", "1.3.0"),
]
```

At least the first should be something like `https://geoserver.data.nhi.nu/geoserver/ows`...

**Comment by JoerivanEngelen** [comment]
Closed in https://github.com/Deltares/imod-qgis/pull/58
